import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/": [
    "",
    "/qianyan",
    {
      text: "介绍",
      icon: "/assets/icon/sheet-plastic.svg",
      prefix: "jieshao/",
      link: "jieshao/",
      collapsible: true,
      expanded: true,
      children: "structure",
    },
    {
      text: "帮助",
      icon: "/assets/icon/book.svg",
      prefix: "zhiling/",
      link: "zhiling/",
      collapsible: true,
      children: [
        {
          text: "菜单帮助help",
          icon: "/assets/icon/book.svg",
          prefix: "help",
          link: "help",
          collapsible: true,
        },
        {
          text: "游戏",
          icon: "/assets/icon/gamepad.svg",
          prefix: "acg/",
          link: "acg/",
          collapsible: true,
          children: [
            "genshin",
            "guangyu",
            "mingchao",
            "juequ0",
            "ark",
            "ba",
            "sr",
            "wws",
            "bf",
            "DeltaForce"
          ],
        },
        {
          text: "音游",
          icon: "/assets/icon/gamepad.svg",
          prefix: "yinyou/",
          link: "yinyou/",
          collapsible: true,
          children: [
            {
              text: "Arcaea",
              icon: "https://drive.nekodayo.top/raw/nekodocs/image/arc.jpg",
              prefix: "arc/",
              link: "arc/",
              collapsible: true,
              children: [
                "b30",
                "arc"
              ],
            },
            {
              text: "Project Sekai",
              icon: "https://drive.nekodayo.top/raw/nekodocs/image/pjsk.jpg",
              prefix: "pjsk/",
              link: "pjsk/",
              collapsible: true,
              children: [
                "uni",
                "haruki",
                "pjsk"
              ],
            },
            "pgr",
            "BangDream",
            "osu",
            "chu",
            "maimai",
            "bs",
          ],
        },
        {
          text: "实用",
          icon: "/assets/icon/thumbs-up.svg",
          prefix: "shiyong/",
          link: "shiyong/",
          collapsible: true,
          children: [
            "train",
            "Multi-Source Daily",
            "status",
            "code",
            "english",
            "bw",
            "music",
            "price",
            "imga",
            "imgts",
            "imgS",
          ],
        },
        {
          text: "娱乐",
          icon: "/assets/icon/face-laugh-squint.svg",
          prefix: "yule/",
          link: "yule/",
          collapsible: true,
          children: [
            "bqb",
            "bqbmaker",
            "dinshi",
            "KFCcrazythursdayvme50",
            "Atri",
            "todaywife",
            "todaycatgirl",
            "qiandao",
            "yiyan",
            "bamotalk",
            "jrrp",
            "abook",
            "cao",
            "hajimi",
            "otto",
            "emoji",
            "mypower",
            "bottle",
            "ciyun",
            "megumin",
            "homo",
            "wordle",
            "jitang",
            "cxh",
            "zhanbu",
            "fabing",
            "oooo",
            "Poke-Plugin",
            "Earth-K-Plugin",
            "L-Plugin",
            "jq",
          ],
        },
        {
          text: "AI",
          icon: "robot",
          prefix: "AI/",
          link: "AI/",
          collapsible: true,
          children: [
            "neko",
            "summarygroup"
          ],
        },
      ],
    },
    {
      text: "注意事项",
      icon: "/assets/icon/splotch.svg",
      prefix: "zhuyi/",
      link: "zhuyi/",
      children: "structure",
    },
    {
      text: "关于",
      icon: "/assets/icon/info.svg",
      prefix: "about/",
      link: "about/",
      children: [
        "me",
        "fankui",
      ],
    },
    "/draw",
    "/qunliao",
    "/zanzhu",
    "/thankU",
  ],
});

